### ISSUE TITLE
.sif unsupported file type? (using Dockerhub version)

### ISSUE THREAD

**Issue by kolydic** [singularityhub/singularity2docker#12]
I'm using a container to try and execute this script. The container was obtained here on Jan 7, 2022: 

https://hub.docker.com/r/jcnitdgp25/singularity2docker

I pulled this docker image as a singularity sandbox to my HPC. Here is my call (with path replaced by $MAINPATH for privacy): 

`singularity exec --cleanenv -B /om3:/om3 $MAINPATH/singularity2docker_latest.sif ./singularity2docker.sh -n univariate_general:new $MAINPATH/univariate_general.sif`

and here is the report I get: 

```
Input Image: $MAINPATH/univariate_general.sif
Cleanup: true

1. Checking for software dependencies, Singularity and Docker...
Found singularity 2.6.0-dist
Found docker Docker version 18.06.3-ce, build d7080c1
Found jq jq-master-v3.8.0-3651-g18d55b6bda

2.  Preparing sandbox for export...
/usr/local/libexec/singularity/functions: line 419: file: command not found
WARNING: Building sandbox as non-root may result in wrong file permissions
/usr/local/libexec/singularity/functions: line 419: file: command not found
ERROR: Unsupported file type: /om3/group/saxelab/LAB_STANDARD_fMRI_CODE/singularity_images_master/univariate_general.sif
Cleaning up...

```

Does anyone have an idea why this might be failing? 
I believe I created my container univariate_general.sif with singularity 3.4.1

**Comment by vsoch** [comment]
It's written in plain sight - your system does not have file:

```
/usr/local/libexec/singularity/functions: line 419: file: command not found
```
See if you can install that.

```bash
$ man file
```
```console
FILE(1)                                                    BSD General Commands Manual                                                   FILE(1)

NAME
     file — determine file type

SYNOPSIS
     file [-bcdEhiklLNnprsSvzZ0] [--apple] [--exclude-quiet] [--extension] [--mime-encoding] [--mime-type] [-e testname] [-F separator]
          [-f namefile] [-m magicfiles] [-P name=value] file ...
     file -C [-m magicfiles]
     file [--help]

DESCRIPTION
     This manual page documents version 5.41 of the file command.
...
```

**Comment by vsoch** [comment]
It's also showing there are problems with what seems to be your singularity install in /usr/local/libexec. Maybe look into those first.

**Comment by kolydic** [comment]
Maybe I'm misunderstanding. Does this group not manage the Dockerhub image [here](https://hub.docker.com/r/jcnitdgp25/singularity2docker)? 

I'm running from inside this container on an HPC, so I'm confused why there would be unmet dependencies at the user level

**Comment by vsoch** [comment]
That looks like it's managed by a user named `jcnitdgp25` which is not me :)

**Comment by vsoch** [comment]
We don't provide a container, just the raw script here assuming that we need to use both docker and singularity natively.
