### ISSUE TITLE
Singularity2docker - jq Error

### ISSUE THREAD

**Issue by ortizem** [singularityhub/singularity2docker#3]
Hi,

I am trying to run singularity2docker.sh but I am getting the following error:

[root@ccl singularity2docker]# ./singularity2docker.sh -n sing2dockertest:latest lolcow.simg

Input Image: lolcow.simg

1. Checking for software dependencies, Singularity and Docker...
Found singularity 2.5.0-dist
Found docker Docker version 1.12.6, build 3a094bd/1.12.6
jq: error while loading shared libraries: libonig.so.2: cannot open shared object file: No such file or directory
Found jq

2.  Preparing sandbox for export...

3.  Exporting metadata...
jq: error while loading shared libraries: libonig.so.2: cannot open shared object file: No such file or directory
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
[root@ccl singularity2docker]#

Do you know a workaround this issue? Please let me know.

**Comment by vsoch** [comment]
Heyo! I'm traveling but should be able to try this out when I'm at a computer. The quick notice is that the library : libonig.so.2:  is missing for jq, so you can try installing that. And any reason to not try running in a container?

**Comment by ortizem** [comment]
Thank you, @vsoch. I will re-install jq and let you know if I have any other issues.

**Comment by vsoch** [comment]
Closing, no report of other issues.
