### ISSUE TITLE
Execution silently terminates at step 2.  Preparing sandbox 

### ISSUE THREAD

**Issue by cgpu** [singularityhub/singularity2docker#4]
Hi,

Thank you for this script!
I am trying to convert a `.simg`. I have (hopefully) followed the instructions from the README. Also, `jq` is installed (shown in the screenshot in the execution message too).

This is what I see after running (on an ec2 instance):

![image](https://user-images.githubusercontent.com/38183826/66757014-1ca9bd00-ee93-11e9-8303-04d9b4f6ae18.png)

```
singularity pull shub://afonsoguerra/GenomeChroniclerDev
singularity2docker/singularity2docker.sh -n gchronicler:101 afonsoguerra-GenomeChroniclerDev-master-latest.simg
```

What am I doing wrong? 🤔 

Thanks in advance,
Christina

**Comment by vsoch** [comment]
It could be that the version of Singularity is too old to support build! This should be fairly easy to debug - for this line:

https://github.com/vsoch/singularity2docker/blob/master/singularity2docker.sh#L127

Remove the end part so the output isn't piped to dev null. Hopefully we'll see the error (and why Singularity exits) and then we can go from there!

**Comment by cgpu** [comment]
Thanks for the feedback @vsoch - will try again and report back for fix. I ended up translating manually and I forgot to check back 🙈.

**Comment by cgpu** [comment]
> Thanks for the feedback @vsoch - will try again and report back for fix. I ended up translating manually and I forgot to check back 🙈.

UPDATE: I ran again for the same container ([this one](https://singularity-hub.org/collections/3539/usage
)), at step 2 I had a question in interactive mode.
The neglected interactive user prompt  might have been causing the abort ?

This is my command and output (`singularity2docker` from my fork https://github.com/cgpu/singularity2docker/commit/56bbb6a4a291cebe0a1c771ecef3ea38f825d7f8)

The Singularity file I would like to translate to Dockerfile is this one:
https://singularity-hub.org/collections/3539/usage

![image](https://user-images.githubusercontent.com/38183826/67275263-226a5880-f4ba-11e9-832d-453cd86b72f9.png)

Let me know if you have enough information.

**Comment by vsoch** [comment]
heyo! Let me give it a test now - I'll need to first pull your container and then see what might be up. While we're waiting (in case it's important) what version of Singularity do you have?

**Comment by vsoch** [comment]
okay just reproduced - it's because Singularity hasn't been consistent with respect to how it outputs it's inspect (json vs not, and then the structure of the json). I need to think about how to best handle this.

**Comment by vsoch** [comment]
hey @cgpu this should fix your issue! https://github.com/vsoch/singularity2docker/pull/6 I went all the way through pulling, building, and then creating the Dockerfile for your container - I didn't actually build a Docker container with it because it's huge, but i suspect you will give this a try! Would you care to review the PR, and if all is well, we can merge into master?

**Comment by cgpu** [comment]
> okay just reproduced - it's because Singularity hasn't been consistent with respect to how it outputs it's inspect (json vs not, and then the structure of the json). I need to think about how to best handle this.

Awesome!  Thanks for checking this so quickly and for the fix, much appreciated. 

Yes the container is super huge ~4 GB. I'll try it first thing tomorrow morning and let you know.  🤞 :

**Comment by vsoch** [comment]
okay it's a plan! Good luck with that container!

**Comment by cgpu** [comment]
> heyo! Let me give it a test now - I'll need to first pull your container and then see what might be up. While we're waiting (in case it's important) what version of Singularity do you have?

I use 3.3.0.
I am running this on ec2. Using ubuntu ami as base, this is my set up in case you need it for testing:

https://github.com/cgpu/cloudies/blob/a09cfa62dcb4f90bc635b774014bacc48db80f3a/aws/ami-scripts/ubuntu_1804_docker_singularity_ami_34435ede.sh#L41

**Comment by cgpu** [comment]
UPDATE 🎉 @vsoch 

Tested and it works for me!

- [X] build successfully completed
- [X] docker container is functional as expected
- [X] `docker push` worked and the container is in my docker hub 
- [X] `docker pull` worked  as well  from my docker hub  (`loadthefalaina/genomechronicler:s2d`)

Here's what it looked like:
[tested.txt](https://github.com/vsoch/singularity2docker/files/3762384/tested.txt)

Question: Can I haz the Dockerfile as well? That would be awesome!

**Comment by vsoch** [comment]
I think it should be in the root of the image - can you check?

**Comment by cgpu** [comment]
> I think it should be in the root of the image - can you check?

Just checked - here it is:

![image](https://user-images.githubusercontent.com/38183826/67400973-591d9d00-f5a6-11e9-8adf-7842b843a8af.png)


```bash
FROM scratch
ADD . /
ENV LD_LIBRARY_PATH /.singularity.d/libs
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LABEL org.label-schema.build-date "Tue,_15_Oct_2019_09:07:08_+0000"
LABEL org.label-schema.build-size "6368MB"
LABEL org.label-schema.schema-version "1.0"
LABEL org.label-schema.usage.singularity.deffile "Singularity"
LABEL org.label-schema.usage.singularity.deffile.bootstrap "docker"
LABEL org.label-schema.usage.singularity.deffile.from "ubuntu:bionic"
LABEL org.label-schema.usage.singularity.version "2.5.2-feature-squashbuild-secbuild-2.5.6e68f9725"
CMD ["/bin/bash", "run_singularity2docker.sh"]
```

If I were to augment this Dockerfile, eg add more installation commands, and if I had a folder named eg `docker`, what other file/folder should I include to be able to `docker build`?

**Comment by vsoch** [comment]
You would need to keep the entire dumped image that is created as a sandbox in /tmp, that we build from. If you like I can add an argument to do `--no-cleanup`

**Comment by cgpu** [comment]
The `--no-cleanup` flag sounds good if it's no hustle, it's already super useful as it is, thank you for writing this!

Feel free to close the issue and also ping me anytime for testing - would be happy to help in anything.

**Comment by vsoch** [comment]
Haha, already pushed and tested, give it a look! If all looks good to you, we can merge.

**Comment by cgpu** [comment]
Ok you're super fast! 

Ran with `--no-cleanup` but `/tmp` is empty for me. Attaching terminal output for you to check.

[test-nocleanup.txt](https://github.com/vsoch/singularity2docker/files/3763016/test-nocleanup.txt)

**Comment by vsoch** [comment]
It tells you that the sandbox is at:

```
Sandbox is at /tmp/singularity2docker.GCImmt
```
if your tmp is entirely empty, is it possible you are cleaning / clearing it with your build?

**Comment by cgpu** [comment]
> It tells you that the sandbox is at:
> 
> ```
> Sandbox is at /tmp/singularity2docker.GCImmt
> ```
> 
> if your tmp is entirely empty, is it possible you are cleaning / clearing it with your build?

Boop! My blooper, I was checking inside the container's `tmp/` 🙊 
It is indeed there `/tmp/singularity2docker.GCImmt`.

So, now if I do: 

```
cd /tmp/singularity2docker.GCImmt
docker build -t loadthefalaina/genomechronicler:s2d-nocleanup-d2d .
```

it should be good.

I built the container from the Dockerfile and all seems good. Thank you!

**Comment by vsoch** [comment]
okay good, then we are good to merge!
