### ISSUE TITLE
error: jq: error (at <stdin>:1): null (null) has no keys

### ISSUE THREAD

**Issue by kforner** [singularityhub/singularity2docker#7]
Hello,

Just got this error trying to convert a SIF image:
```
singularity pull docker://godlovedc/lolcow
./singularity2docker.sh -n lolcow_sing ./lolcow_latest.sif

Input Image: ./lolcow_latest.sif
Cleanup: true

1. Checking for software dependencies, Singularity and Docker...
Found singularity singularity version 3.5.0
Found docker Docker version 19.03.5, build 633a0ea838
Found jq jq-1.5-1-a5b5cbe

2.  Preparing sandbox for export...
INFO:    Starting build...
INFO:    Creating sandbox directory...
INFO:    Build complete: /tmp/singularity2docker.PT9uBK

3.  Exporting metadata...
WARNING: No metadata partition, searching in container...
jq: error (at <stdin>:1): null (null) has no keys
```
```
singularity version
3.5.0
docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:50:12 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:48:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Comment by vsoch** [comment]
This unfortunately looks like it's a result of Singularity not being consistent with respect to the format of the metadata:
```
3.  Exporting metadata...
WARNING: No metadata partition, searching in container...
jq: error (at <stdin>:1): null (null) has no keys
```
And in fact I even noted it here!

https://github.com/vsoch/singularity2docker/blob/master/singularity2docker.sh#L156

Could you do:

```bash
singularity inspect -l --json lolcow_latest.sif
```
And tell me what you see?

**Comment by kforner** [comment]
Thanks for this fast answer. 
This was also my conclusion: I fixed the jq by adding .data

```
 singularity inspect -l --json ./lolcow_latest.sif
WARNING: No metadata partition, searching in container...
{
	"data": {
		"attributes": {
			"labels": {
				"org.label-schema.build-date": "Monday_25_November_2019_18:39:7_CET",
				"org.label-schema.schema-version": "1.0",
				"org.label-schema.usage.singularity.deffile.bootstrap": "docker",
				"org.label-schema.usage.singularity.deffile.from": "godlovedc/lolcow",
				"org.label-schema.usage.singularity.version": "3.5.0"
			}
		}
	},
	"type": "container"
}
```

so I edited the `jq`lines:
```
entries=$(singularity inspect -l --json ${image} | jq -r '.data .attributes .labels')
and
value=$(singularity inspect -l --json ${image} | jq -r ".data .attributes .labels[\"${key}\"]")
```
now the image is generated but does not work:
```
docker run -ti --rm lolcow_sing 
/bin/sh: 1: fortune: not found
/bin/sh: 1: cowsay: not found
/bin/sh: 1: lolcat: not found
```
It seems to be a matter of path since this works:

```
docker run -ti --rm lolcow_sing  sh -c "/usr/games/fortune  | /usr/games/cowsay"
```

**Comment by vsoch** [comment]
Perfect - yes the spec requires data, and then nested attributes and labels, but the conversion from Singularity (in python bash v2.5) to GoLang broke that consistency - we've had just attributes and labels for easily a year or two now, and it looks like in 3.5 they finally fixed it to be correct again.

What I can try to do is add some check for the attribute.

For the environment, the paths (used to be in an /environment file, I'm guessing that is different too? See this line:

https://github.com/vsoch/singularity2docker/blob/master/singularity2docker.sh#L171

**Comment by vsoch** [comment]
I'm pulling the container now to see if I can fuss around a bit too.

**Comment by kforner** [comment]
does not seem to be this since cat /environment is void both in SIF and in the docker.
The PATH must be set by another way.
Have to leave now...
Thanks for your help

**Comment by vsoch** [comment]
Sure thing! I'll see if I can look into this, I'm not a core Singularity developer so I'm not in sync with how they are changing it. I'll do my best to see what I can figure out.

**Comment by vsoch** [comment]
okay looks like the environment we need was all imported from Docker (as we just did) so we need to account for those files:
```bash
Singularity> ls /.singularity.d/env/
01-base.sh  10-docker2singularity.sh  90-environment.sh  94-appsbase.sh  95-apps.sh  99-base.sh  99-runtimevars.sh
```

**Comment by vsoch** [comment]
okay we're good!
```
$ docker run -ti --rm newcontainer:tag 
 ____________________________________
/ You will pioneer the first Martian \
\ colony.                            /
 ------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```
I'll have a PR for you shortly.

**Comment by vsoch** [comment]
okay, give this a go @kforner when you are back at it, should resolve both issues we discussed:

https://github.com/vsoch/singularity2docker/pull/8

Thanks for opening the issue!

**Comment by kforner** [comment]
This works perfectly. Thanks !!

**Comment by vsoch** [comment]
Great! Thanks for letting me know - I'll merge so others don't hit the errors that you did. Thanks for reporting!
