### ISSUE TITLE
integration in singularity ?

### ISSUE THREAD

**Issue by kforner** [singularityhub/singularity2docker#9]
Hi again,

Have you tried reaching out to the singularity team to ask if they are interested in integrating your script in their software ? 
It would make perfect sense to me since they already have the conversion from docker to singularity...

**Comment by vsoch** [comment]
We could, but the team is fairly overwhelmed with standard issues and just regular work on Singularity. If I guessed, I'd say that they would suggest just maintaining it separately. 

Would it help if I moved it over to the [containertools](https://www.github.com/singularityhub) (singularityhub) organization? That's where SIngularity Registry Server, Singularity Python, and a few other supporting tools are maintained.

**Comment by kforner** [comment]
My point was that it could help with the maintenance if it were part of the official singularity ecosystem.  
From what you said **containertools** seems to fairly adequate, so yes, IMHO sounds like a good idea.

**Comment by vsoch** [comment]
okay, happy to do that!

**Comment by vsoch** [comment]
All set. http://github.com/singularityhub/singularity2docker
